name: Custom Rom Builder Samsung Galaxy A11/M11

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image '
        required: true
        default: 'https://sourceforge.net/projects/andyyan-gsi/files/lineage-19.x/lineage-19.1-20230715-UNOFFICIAL-a64_bgN.img.xz'        
      ARCH:
        description: 'ARM64 or ARM32?'
        required: true
        default: '32'                
      VNDK:
        description: '29 or 30'
        required: true
        default: '29'
      NAME:
        description: 'Rom Name'
        required: true
        default: 'LineageOS_19.1_A11_M11_ARM32_Gapps'                

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        VNDK_INPUT="${{ github.event.inputs.VNDK }}"
        DOWNLOAD_URL=""
    
        if [[ "$VNDK_INPUT" == "30" ]]; then
          echo "VNDK is 30, will use kernel 4.9.227+ with vndk30 provided by @atul2737 and @Ifoodplayer."
          DOWNLOAD_URL="https://sourceforge.net/projects/gsi-for-m11/files/M11_DevOps_7GBSuper/a11q.zip"
        else
          echo "VNDK is not 30, will use default settings from @smiley9000 sir (kernel 4.9.186 with vndk29)."
          DOWNLOAD_URL="https://sourceforge.net/projects/gsi-for-m11/files/M11_DevOps_7GBSuper/a11q_vndk29.zip"
        fi

        wget "$DOWNLOAD_URL"
        unzip "$(basename "$DOWNLOAD_URL")"
        rm -r "$(basename "$DOWNLOAD_URL")"

    - name: Downloading your GSI
      run: |
        wget -P "./temp" ${{ github.event.inputs.GSI }} 
        chmod 755 *
        chmod 755 ./bin/*

    - name: Building
      run: |
        ./arm${{ github.event.inputs.ARCH }}_git
        
    - name: Uploading The Zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.NAME }}   # Replace with a suitable name
        path: ./zip/Custom_Rom_SDM450.zip
