name: Custom Rom Builder Samsung Galaxy A11/M11

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'direct link for Gsi image'
        required: true
        default: 'https://github.com/Doze-off/manifest/releases/download/2025-07-12/Infinity-x-2.9_treble_arm64_bgN-ab-Official-EOL.img.xz'        
      ARCH:
        description: 'ARM64 or ARM32?'
        required: true
        type: choice
        options:
          - '64'
          - '32'
        default: '64'
      VNDK:
        description: 'vndk29 or vndk30 or vndk32 or vndk33'
        required: true
        type: choice
        options:
          - '33'
          - '32'
          - '30'
          - '29'
        default: '33'
      NAME:
        description: 'Rom Name'
        required: true
        default: 'InfinityX_2.9_A11_M11_ARM64_Gapps_5GBSuper'
      RELEASE:
        description: 'Whether to make a release or not'
        required: true
        type: boolean
        default: false

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        VNDK_INPUT="${{ github.event.inputs.VNDK }}"
        DOWNLOAD_URL=""
    
        if [[ "$VNDK_INPUT" == "33" ]]; then
          echo "VNDK is 33, will use kernel 4.9.337 with vndk33 (ifoodplayer v1.4.0 vendor + custom kernel)."
          DOWNLOAD_URL="https://github.com/WPHorhe/Custom-Rom-Builder-For-Samsung-Galaxy-SDM439-SDM450/releases/download/vndk33-preset/a11q_vndk33.zip"
        elif [[ "$VNDK_INPUT" == "32" ]]; then
          echo "VNDK is 32, will use kernel 4.9.305 with vndk32 provided by @Ifoodplayer."
          DOWNLOAD_URL="https://sourceforge.net/projects/gsi-for-m11/files/M11_DevOps_5GBSuper/a11q_vndk32.zip"
        elif [[ "$VNDK_INPUT" == "30" ]]; then
          echo "VNDK is 30, will use kernel 4.9.227 with vndk30 provided by @atul2737 and @Ifoodplayer."
          DOWNLOAD_URL="https://sourceforge.net/projects/gsi-for-m11/files/M11_DevOps_5GBSuper/a11q_vndk30.zip"
        else
          echo "Default VNDK is 29, will use default settings from @smiley9000 sir (kernel 4.9.186 with vndk29)."
          DOWNLOAD_URL="https://sourceforge.net/projects/gsi-for-m11/files/M11_DevOps_5GBSuper/a11q_vndk29.zip"
        fi

        wget "$DOWNLOAD_URL"
        unzip "$(basename "$DOWNLOAD_URL")"
        rm -r "$(basename "$DOWNLOAD_URL")"

    - name: Downloading your GSI
      run: |
        wget -P "./temp" ${{ github.event.inputs.GSI }} 
        chmod 755 *
        chmod 755 ./bin/*

    - name: Building
      run: |
        ./arm${{ github.event.inputs.ARCH }}_git

    - name: Prepare Files (Unzip) for Artifact
      run: |
        mkdir -p ./extracted
        unzip ./zip/Custom_Rom_SDM450.zip -d ./extracted

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.event.inputs.NAME }}
        path: ./extracted/

    - name: Prepare Files (Rename) for Release
      if: github.event.inputs.RELEASE == 'true'
      run: cp ./zip/Custom_Rom_SDM450.zip "./zip/${{ github.event.inputs.NAME }}.zip"

    - name: Get current date
      if: github.event.inputs.RELEASE == 'true'
      run: |
        echo "RELEASE_DATE=$(TZ='Asia/Taipei' date +'%Y%m%d_%H%M')" >> $GITHUB_ENV

    - name: Create Release
      if: github.event.inputs.RELEASE == 'true'
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ env.RELEASE_DATE }}
        name: ${{ github.event.inputs.NAME }}
        body: "This is an auto-generated Custom Rom."
        draft: true
        prerelease: false
        files: |
          ./zip/${{ github.event.inputs.NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
